# Generated by Django 4.1.2 on 2022-11-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_category_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новости'},
        ),
    ]
