# Generated by Django 4.1.2 on 2022-11-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_options_alter_news_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Pands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname_user', models.CharField(max_length=150, verbose_name='Название пользователя')),
                ('name_user', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('surname_user', models.CharField(max_length=100, verbose_name='Фамилия пользователя')),
                ('email_user', models.EmailField(max_length=254, verbose_name='Почта пользователя')),
                ('password_user', models.CharField(max_length=100, verbose_name='Пароль пользователя')),
                ('is_admin_user', models.BooleanField(default=False, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Пользователи Панды',
            },
        ),
    ]
