# Generated by Django 4.1.2 on 2022-11-02 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_users_pands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='news.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='users_pands',
            name='is_admin_user',
            field=models.BooleanField(blank=True, default=False, verbose_name='Администратор'),
        ),
    ]
