# Generated by Django 4.1.2 on 2022-11-02 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_category_alter_users_pands_is_admin_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='users_pands',
            options={'ordering': ['id'], 'verbose_name': 'Пользователи Панды'},
        ),
    ]
